# Generated by Django 5.0.4 on 2024-05-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_email', models.EmailField(default='email@gmail.com', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lead_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('lead_contact', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_username', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('log_password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('log_date', models.DateField(auto_now_add=True, null=True)),
                ('log_time', models.TimeField(auto_now_add=True, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_staff', models.IntegerField(default=0)),
                ('active_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Leads_assignto_tc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Reason', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Assign_Date', models.DateField(auto_now_add=True, null=True)),
                ('Allocate_time', models.TimeField(default='00:00:00')),
                ('Update_Date', models.DateField(null=True)),
                ('Next_update_date', models.DateField(null=True)),
                ('Update_Action', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('TC_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.employeeregister_details')),
                ('leadId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
        migrations.AddField(
            model_name='employeeregister_details',
            name='logreg_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.logregister_details'),
        ),
    ]
